language: ruby

before_install: gem install bundler -v 1.11.2

before_script:
  - sudo apt-get install pdftk

branches:
  only:
    - "master"

addons:
  code_climate:
    repo_token: $CODECLIMATE_REPO_TOKEN
